name: Update the README.md

on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current date and time
        id: data_now
        run: |
          echo "data_now=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Update the README.md
        run: |
          echo "Latest update: ${{ steps.data_now.outputs.data_now }}" >> README.md
      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Aggiornato il README con l'ultima esecuzione del workflow"
          git push